platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

def pods
	pod 'MJRefresh'
	pod 'YYKit'
    pod 'YTKNetwork'
	pod 'FDFullscreenPopGesture' # use QMUIKit
	# pod 'pop'
#	pod 'IQKeyboardManager' # use QMUIKit
	pod 'Masonry'
	pod 'SDWebImage' # use YYKit ? 
#	pod 'MBProgressHUD' # use QMUIKit
	pod 'FormatterKit' # 格式化
#	pod 'US2FormValidator' # 校验 暂时未用到
#	pod 'Appirater'   # 评分 暂时未用到
#	pod 'MZTimerLabel' # 倒计时 暂时未用到
#	pod 'WebViewJavascriptBridge' # java bridge 暂时未用到
	pod 'WZProtocolInterceptor'
	# pod 'EAIntroView' # 开屏引导图
#	pod 'DZNSegmentedControl'
#	pod 'NJKWebViewProgress' # 网页进度条 暂时未用到
#	pod 'HMSegmentedControl', :git => 'https://github.com/Minlison/HMSegmentedControl.git'  # segment 暂时未用到
	# pod 'Qiniu' # 七牛
#	pod 'EBForeNotification' # 处于前台时展示跟系统完全一样的推送弹窗和声音
#	pod 'KVOController' # KVO 暂时未用到
	# pod 'lottie-ios' # 动画
	#pod 'Aspects' # AOP 切面编程
#    pod 'TTTAttributedLabel' # 属性字符串 label 暂时未用到
    pod 'QMUIKit' # UI
    pod 'BeeHive' # 架构
#    pod 'FDStackView' # stackView 适配
    pod 'CRToast' # 导航栏顶部提示
    #pod 'ChameleonFramework' # 颜色
    #pod 'FontAwesomeKit' # 字体
#    pod 'ObjectiveSugar' # Foundation 的分类 ThirdCode 源码管理
    pod 'SAMKeychain' # 钥匙串
    pod 'FBMemoryProfiler', :configurations => ['Debug']
    pod 'CocoaLumberjack'
end

def testPods
    pods
    pod 'Quick'
    pod 'Nimble'
end

target 'MLSProject' do
	pods
end

target 'MLSProjectTests' do
testPods
end

