platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

def UmengUDPlusPods
    # 统计
    pod 'umeng/umerror', :path    => './MLSProject/ThirdLib/umeng' # dependency analytics
    pod 'umeng/analytics', :path    => './MLSProject/ThirdLib/umeng'
    # 分享
    pod 'umeng/share', :path    => './MLSProject/ThirdLib/umeng'
    # 推送
    pod 'umeng/push', :path    => './MLSProject/ThirdLib/umeng'
end

def UMengNormalPods
    # 统计
    pod 'umeng/analytics', :path    => './MLSProject/ThirdLib/umeng'
    # 推送
    pod 'umeng/umessage', :path    => './MLSProject/ThirdLib/umeng'
    #    pod 'umeng/umessageidfa', :path    => './MLSProject/ThirdLib/umeng'
    # 分享
    pod 'umeng/social', :path    => './MLSProject/ThirdLib/umeng'
    #    pod 'umeng/idfa', :path    => './MLSProject/ThirdLib/umeng'
end

def pods
#    pod 'MJRefresh'
    pod 'YYKit', :git => 'https://github.com/Minlison/YYKit'
#    pod 'YTKNetwork'
    pod 'YTKNetwork', :path    => './MLSProject/ThirdCode/YTKNetwork'
#    pod 'FDFullscreenPopGesture' # 源码
    pod 'pop'
    pod 'IQKeyboardManager' #
	pod 'Masonry'
	pod 'SDWebImage' # use YYKit ? 
#	pod 'MBProgressHUD' # use QMUIKit
#    pod 'FormatterKit' # 格式化
#    pod 'US2FormValidator', :path    => './MLSProject/ThirdCode/US2FormValidator' # 校验 源码
#	pod 'Appirater'   # 评分 暂时未用到
#	pod 'MZTimerLabel' # 源码
#	pod 'WebViewJavascriptBridge' # java bridge 暂时未用到
	pod 'WZProtocolInterceptor'
	# pod 'EAIntroView' # 开屏引导图
#	pod 'DZNSegmentedControl'
#	pod 'NJKWebViewProgress' # 网页进度条 暂时未用到
#	pod 'HMSegmentedControl', :git => 'https://github.com/Minlison/HMSegmentedControl.git'  # 源码
	# pod 'Qiniu' # 七牛
#	pod 'EBForeNotification' # 处于前台时展示跟系统完全一样的推送弹窗和声音
    pod 'KVOController' # KVO 暂时未用到
	# pod 'lottie-ios' # 动画
    pod 'Aspects' # AOP 切面编程
    pod 'TTTAttributedLabel' # 属性字符串 label
#    pod 'QMUIKit' # 源码
    pod 'BeeHive' # 架构
#    pod 'FDStackView' # stackView 适配
    pod 'CRToast' # 导航栏顶部提示
    #pod 'ChameleonFramework' # 颜色
    #pod 'FontAwesomeKit' # 字体
#    pod 'ObjectiveSugar' # Foundation 的分类 ThirdCode 源码管理
    pod 'SAMKeychain' # 钥匙串
#    pod 'FBMemoryProfiler', :configurations => ['Debug']
    pod 'CocoaLumberjack'
    #    pod 'STPopup' # 源码管理
    pod 'Reveal-SDK','~> 4', :configurations => ['Debug']

    pod 'pgyer', :path    => './MLSProject/ThirdLib/pgyer', :configurations => ['Debug','ADHoc','ADHocOnline']
    pod 'umeng/thirdparties', :path    => './MLSProject/ThirdLib/umeng'
    pod 'umeng/common', :path    => './MLSProject/ThirdLib/umeng'
    # 统计
    pod 'umeng/analytics', :path    => './MLSProject/ThirdLib/umeng'
    # 推送
    pod 'umeng/umessage', :path    => './MLSProject/ThirdLib/umeng'
    #    pod 'umeng/umessageidfa', :path    => './MLSProject/ThirdLib/umeng'
    # 分享
    pod 'umeng/social', :path    => './MLSProject/ThirdLib/umeng'
    #    pod 'umeng/idfa', :path    => './MLSProject/ThirdLib/umeng'
    
    pod 'AMapLocation-NO-IDFA' # 定位 SDK
end



target 'MLSProject' do
	pods
end

