//
//  AppConfigConstString.h
//  MLSProject
//
//  Created by MinLison on 2017/10/10.
//  Copyright © 2017年 minlison. All rights reserved.
//

#import <Foundation/Foundation.h>
#ifndef AppConfigConstString_h
#define AppConfigConstString_h

FOUNDATION_EXTERN NSString *APP_DOWNLOAD_URL;
FOUNDATION_EXTERN NSString *APP_ID;
FOUNDATION_EXTERN NSString *UMENG_APPKEY;
FOUNDATION_EXTERN NSString *UMENG_MASTER_SECRET;
FOUNDATION_EXTERN NSString *UMENG_QQAPPID;
FOUNDATION_EXTERN NSString *UMENG_QQAPPKEY;
FOUNDATION_EXTERN NSString *UMENG_WEBCATAPPID;
FOUNDATION_EXTERN NSString *UMENG_WEBCATAPPKEY;
FOUNDATION_EXTERN NSString *UMENG_XINLANGAPPSECRET;
FOUNDATION_EXTERN NSString *UMENG_XINLNAGAPPKEY;
FOUNDATION_EXTERN NSString *UMENG_XINLANG_REDIRECT;

#endif
