//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

#import "R.generated.h"

/// NSObject no func and structs

/// This `R.image` struct is generated, and contains static references to 52 images.
@implementation UIImage (Image) 

/// `[[UIImage imageNamed:@"launchImage"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)launchImageRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"launchImage"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"launchImage"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)launchImage {
     return [[UIImage imageNamed:@"launchImage"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"line"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)line {
     return [[UIImage imageNamed:@"line"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"line"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)lineRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"line"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"loading_pic"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading_picRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"loading_pic"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"loading_pic"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading_pic {
     return [[UIImage imageNamed:@"loading_pic"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"maskJpg"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)maskJpgRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"maskJpg"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"maskJpg"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)maskJpg {
     return [[UIImage imageNamed:@"maskJpg"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"nav_bar_shadows"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)nav_bar_shadowsRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"nav_bar_shadows"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"nav_bar_shadows"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)nav_bar_shadows {
     return [[UIImage imageNamed:@"nav_bar_shadows"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"nav_ic_back_black"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)nav_ic_back_blackRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"nav_ic_back_black"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"nav_ic_back_black"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)nav_ic_back_black {
     return [[UIImage imageNamed:@"nav_ic_back_black"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"nav_ic_back_white"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)nav_ic_back_whiteRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"nav_ic_back_white"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"nav_ic_back_white"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)nav_ic_back_white {
     return [[UIImage imageNamed:@"nav_ic_back_white"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"none_pic"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)none_pic {
     return [[UIImage imageNamed:@"none_pic"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"none_pic"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)none_picRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"none_pic"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"player_bottom_shadow"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_bottom_shadow {
     return [[UIImage imageNamed:@"player_bottom_shadow"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"player_bottom_shadow"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_bottom_shadowRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"player_bottom_shadow"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"player_fast_backward"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_fast_backwardRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"player_fast_backward"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"player_fast_backward"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_fast_backward {
     return [[UIImage imageNamed:@"player_fast_backward"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"player_fast_forward"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_fast_forwardRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"player_fast_forward"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"player_fast_forward"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_fast_forward {
     return [[UIImage imageNamed:@"player_fast_forward"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"player_ic_btn"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_ic_btnRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"player_ic_btn"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"player_ic_btn"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_ic_btn {
     return [[UIImage imageNamed:@"player_ic_btn"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"player_ic_max"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_ic_maxRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"player_ic_max"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"player_ic_max"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_ic_max {
     return [[UIImage imageNamed:@"player_ic_max"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"player_ic_play"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_ic_play {
     return [[UIImage imageNamed:@"player_ic_play"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"player_ic_play"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_ic_playRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"player_ic_play"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"player_ic_stop"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_ic_stop {
     return [[UIImage imageNamed:@"player_ic_stop"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"player_ic_stop"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_ic_stopRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"player_ic_stop"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"player_pattern_error"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pattern_error {
     return [[UIImage imageNamed:@"player_pattern_error"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"player_pattern_error"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pattern_errorRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"player_pattern_error"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"player_pic_light1"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light1RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"player_pic_light1"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"player_pic_light1"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light1 {
     return [[UIImage imageNamed:@"player_pic_light1"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"player_pic_light10"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light10 {
     return [[UIImage imageNamed:@"player_pic_light10"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"player_pic_light10"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light10RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"player_pic_light10"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"player_pic_light11"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light11RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"player_pic_light11"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"player_pic_light11"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light11 {
     return [[UIImage imageNamed:@"player_pic_light11"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"player_pic_light12"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light12RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"player_pic_light12"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"player_pic_light12"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light12 {
     return [[UIImage imageNamed:@"player_pic_light12"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"player_pic_light13"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light13 {
     return [[UIImage imageNamed:@"player_pic_light13"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"player_pic_light13"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light13RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"player_pic_light13"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"player_pic_light14"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light14RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"player_pic_light14"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"player_pic_light14"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light14 {
     return [[UIImage imageNamed:@"player_pic_light14"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"player_pic_light15"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light15RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"player_pic_light15"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"player_pic_light15"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light15 {
     return [[UIImage imageNamed:@"player_pic_light15"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"player_pic_light16"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light16 {
     return [[UIImage imageNamed:@"player_pic_light16"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"player_pic_light16"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light16RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"player_pic_light16"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"player_pic_light2"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light2RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"player_pic_light2"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"player_pic_light2"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light2 {
     return [[UIImage imageNamed:@"player_pic_light2"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"player_pic_light3"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light3RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"player_pic_light3"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"player_pic_light3"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light3 {
     return [[UIImage imageNamed:@"player_pic_light3"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"player_pic_light4"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light4RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"player_pic_light4"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"player_pic_light4"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light4 {
     return [[UIImage imageNamed:@"player_pic_light4"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"player_pic_light5"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light5 {
     return [[UIImage imageNamed:@"player_pic_light5"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"player_pic_light5"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light5RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"player_pic_light5"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"player_pic_light6"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light6RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"player_pic_light6"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"player_pic_light6"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light6 {
     return [[UIImage imageNamed:@"player_pic_light6"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"player_pic_light7"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light7 {
     return [[UIImage imageNamed:@"player_pic_light7"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"player_pic_light7"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light7RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"player_pic_light7"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"player_pic_light8"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light8RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"player_pic_light8"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"player_pic_light8"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light8 {
     return [[UIImage imageNamed:@"player_pic_light8"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"player_pic_light9"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light9RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"player_pic_light9"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"player_pic_light9"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light9 {
     return [[UIImage imageNamed:@"player_pic_light9"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"player_pic_vol0"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol0RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"player_pic_vol0"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"player_pic_vol0"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol0 {
     return [[UIImage imageNamed:@"player_pic_vol0"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"player_pic_vol1"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol1RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"player_pic_vol1"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"player_pic_vol1"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol1 {
     return [[UIImage imageNamed:@"player_pic_vol1"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"player_pic_vol10"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol10RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"player_pic_vol10"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"player_pic_vol10"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol10 {
     return [[UIImage imageNamed:@"player_pic_vol10"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"player_pic_vol11"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol11 {
     return [[UIImage imageNamed:@"player_pic_vol11"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"player_pic_vol11"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol11RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"player_pic_vol11"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"player_pic_vol12"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol12 {
     return [[UIImage imageNamed:@"player_pic_vol12"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"player_pic_vol12"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol12RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"player_pic_vol12"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"player_pic_vol13"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol13 {
     return [[UIImage imageNamed:@"player_pic_vol13"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"player_pic_vol13"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol13RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"player_pic_vol13"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"player_pic_vol14"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol14RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"player_pic_vol14"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"player_pic_vol14"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol14 {
     return [[UIImage imageNamed:@"player_pic_vol14"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"player_pic_vol15"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol15 {
     return [[UIImage imageNamed:@"player_pic_vol15"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"player_pic_vol15"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol15RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"player_pic_vol15"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"player_pic_vol16"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol16RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"player_pic_vol16"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"player_pic_vol16"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol16 {
     return [[UIImage imageNamed:@"player_pic_vol16"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"player_pic_vol2"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol2 {
     return [[UIImage imageNamed:@"player_pic_vol2"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"player_pic_vol2"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol2RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"player_pic_vol2"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"player_pic_vol3"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol3RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"player_pic_vol3"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"player_pic_vol3"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol3 {
     return [[UIImage imageNamed:@"player_pic_vol3"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"player_pic_vol4"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol4 {
     return [[UIImage imageNamed:@"player_pic_vol4"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"player_pic_vol4"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol4RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"player_pic_vol4"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"player_pic_vol5"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol5 {
     return [[UIImage imageNamed:@"player_pic_vol5"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"player_pic_vol5"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol5RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"player_pic_vol5"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"player_pic_vol6"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol6 {
     return [[UIImage imageNamed:@"player_pic_vol6"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"player_pic_vol6"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol6RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"player_pic_vol6"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"player_pic_vol7"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol7RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"player_pic_vol7"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"player_pic_vol7"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol7 {
     return [[UIImage imageNamed:@"player_pic_vol7"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"player_pic_vol8"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol8RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"player_pic_vol8"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"player_pic_vol8"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol8 {
     return [[UIImage imageNamed:@"player_pic_vol8"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"player_pic_vol9"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol9RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"player_pic_vol9"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"player_pic_vol9"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol9 {
     return [[UIImage imageNamed:@"player_pic_vol9"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"player_top_shadow"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_top_shadowRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"player_top_shadow"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"player_top_shadow"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_top_shadow {
     return [[UIImage imageNamed:@"player_top_shadow"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"player_wifi_error"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_wifi_error {
     return [[UIImage imageNamed:@"player_wifi_error"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"player_wifi_error"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_wifi_errorRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"player_wifi_error"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"restrictedshineTiff"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)restrictedshineTiffRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"restrictedshineTiff"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"restrictedshineTiff"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)restrictedshineTiff {
     return [[UIImage imageNamed:@"restrictedshineTiff"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}
@end



/// This `R.string.appConst` struct is generated, and contains static references to 3 localization keys.
@implementation NSString (AppConst) 

/// Base translation: 刷新
/// 
/// Locales: Base, en, zh-Hans
+ (NSString *)app_Refresh {
     return NSLocalizedStringWithDefaultValue(@"App_Refresh",@"AppConst",[NSBundle mainBundle],@"刷新",@"");
}


/// Base translation: 加载失败，请检查网络链接！
/// 
/// Locales: Base, en, zh-Hans
+ (NSString *)app_NeworkError {
     return NSLocalizedStringWithDefaultValue(@"App_NeworkError",@"AppConst",[NSBundle mainBundle],@"加载失败，请检查网络链接！",@"");
}


/// Base translation: 确定
/// 
/// Locales: Base, en, zh-Hans
+ (NSString *)app_Sure {
     return NSLocalizedStringWithDefaultValue(@"App_Sure",@"AppConst",[NSBundle mainBundle],@"确定",@"");
}
@end



/// UIColor no func and structs

/// UIFont no func and structs

/// UINib no func and structs

/// UINib no func and structs
