//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

/// NSObject no func and structs

/// This `R.image` struct is generated, and contains static references to 53 images.

@interface UIImage (Image) 

/// `[[UIImage imageNamed:@"icon_update"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)icon_update;

/// `[[UIImage imageNamed:@"icon_update"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)icon_updateRenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"launchImage"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)launchImageRenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"launchImage"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)launchImage;


/// `[[UIImage imageNamed:@"line"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)line;

/// `[[UIImage imageNamed:@"line"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)lineRenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"loading_pic"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading_picRenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"loading_pic"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading_pic;


/// `[[UIImage imageNamed:@"maskJpg"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)maskJpgRenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"maskJpg"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)maskJpg;


/// `[[UIImage imageNamed:@"nav_bar_shadows"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)nav_bar_shadowsRenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"nav_bar_shadows"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)nav_bar_shadows;


/// `[[UIImage imageNamed:@"nav_ic_back_black"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)nav_ic_back_blackRenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"nav_ic_back_black"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)nav_ic_back_black;


/// `[[UIImage imageNamed:@"nav_ic_back_white"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)nav_ic_back_whiteRenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"nav_ic_back_white"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)nav_ic_back_white;


/// `[[UIImage imageNamed:@"none_pic"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)none_pic;

/// `[[UIImage imageNamed:@"none_pic"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)none_picRenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"player_bottom_shadow"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_bottom_shadow;

/// `[[UIImage imageNamed:@"player_bottom_shadow"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_bottom_shadowRenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"player_fast_backward"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_fast_backwardRenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"player_fast_backward"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_fast_backward;


/// `[[UIImage imageNamed:@"player_fast_forward"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_fast_forwardRenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"player_fast_forward"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_fast_forward;


/// `[[UIImage imageNamed:@"player_ic_btn"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_ic_btnRenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"player_ic_btn"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_ic_btn;


/// `[[UIImage imageNamed:@"player_ic_max"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_ic_maxRenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"player_ic_max"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_ic_max;


/// `[[UIImage imageNamed:@"player_ic_play"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_ic_play;

/// `[[UIImage imageNamed:@"player_ic_play"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_ic_playRenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"player_ic_stop"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_ic_stop;

/// `[[UIImage imageNamed:@"player_ic_stop"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_ic_stopRenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"player_pattern_error"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pattern_error;

/// `[[UIImage imageNamed:@"player_pattern_error"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pattern_errorRenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"player_pic_light1"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light1RenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"player_pic_light1"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light1;


/// `[[UIImage imageNamed:@"player_pic_light10"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light10;

/// `[[UIImage imageNamed:@"player_pic_light10"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light10RenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"player_pic_light11"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light11RenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"player_pic_light11"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light11;


/// `[[UIImage imageNamed:@"player_pic_light12"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light12RenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"player_pic_light12"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light12;


/// `[[UIImage imageNamed:@"player_pic_light13"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light13;

/// `[[UIImage imageNamed:@"player_pic_light13"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light13RenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"player_pic_light14"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light14RenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"player_pic_light14"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light14;


/// `[[UIImage imageNamed:@"player_pic_light15"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light15RenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"player_pic_light15"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light15;


/// `[[UIImage imageNamed:@"player_pic_light16"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light16;

/// `[[UIImage imageNamed:@"player_pic_light16"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light16RenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"player_pic_light2"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light2RenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"player_pic_light2"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light2;


/// `[[UIImage imageNamed:@"player_pic_light3"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light3RenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"player_pic_light3"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light3;


/// `[[UIImage imageNamed:@"player_pic_light4"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light4RenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"player_pic_light4"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light4;


/// `[[UIImage imageNamed:@"player_pic_light5"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light5;

/// `[[UIImage imageNamed:@"player_pic_light5"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light5RenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"player_pic_light6"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light6RenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"player_pic_light6"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light6;


/// `[[UIImage imageNamed:@"player_pic_light7"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light7;

/// `[[UIImage imageNamed:@"player_pic_light7"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light7RenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"player_pic_light8"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light8RenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"player_pic_light8"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light8;


/// `[[UIImage imageNamed:@"player_pic_light9"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light9RenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"player_pic_light9"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_light9;


/// `[[UIImage imageNamed:@"player_pic_vol0"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol0RenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"player_pic_vol0"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol0;


/// `[[UIImage imageNamed:@"player_pic_vol1"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol1RenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"player_pic_vol1"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol1;


/// `[[UIImage imageNamed:@"player_pic_vol10"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol10RenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"player_pic_vol10"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol10;


/// `[[UIImage imageNamed:@"player_pic_vol11"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol11;

/// `[[UIImage imageNamed:@"player_pic_vol11"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol11RenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"player_pic_vol12"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol12;

/// `[[UIImage imageNamed:@"player_pic_vol12"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol12RenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"player_pic_vol13"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol13;

/// `[[UIImage imageNamed:@"player_pic_vol13"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol13RenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"player_pic_vol14"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol14RenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"player_pic_vol14"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol14;


/// `[[UIImage imageNamed:@"player_pic_vol15"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol15;

/// `[[UIImage imageNamed:@"player_pic_vol15"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol15RenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"player_pic_vol16"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol16RenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"player_pic_vol16"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol16;


/// `[[UIImage imageNamed:@"player_pic_vol2"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol2;

/// `[[UIImage imageNamed:@"player_pic_vol2"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol2RenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"player_pic_vol3"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol3RenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"player_pic_vol3"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol3;


/// `[[UIImage imageNamed:@"player_pic_vol4"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol4;

/// `[[UIImage imageNamed:@"player_pic_vol4"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol4RenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"player_pic_vol5"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol5;

/// `[[UIImage imageNamed:@"player_pic_vol5"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol5RenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"player_pic_vol6"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol6;

/// `[[UIImage imageNamed:@"player_pic_vol6"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol6RenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"player_pic_vol7"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol7RenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"player_pic_vol7"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol7;


/// `[[UIImage imageNamed:@"player_pic_vol8"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol8RenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"player_pic_vol8"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol8;


/// `[[UIImage imageNamed:@"player_pic_vol9"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol9RenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"player_pic_vol9"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_pic_vol9;


/// `[[UIImage imageNamed:@"player_top_shadow"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_top_shadowRenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"player_top_shadow"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_top_shadow;


/// `[[UIImage imageNamed:@"player_wifi_error"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_wifi_error;

/// `[[UIImage imageNamed:@"player_wifi_error"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)player_wifi_errorRenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"restrictedshineTiff"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)restrictedshineTiffRenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"restrictedshineTiff"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)restrictedshineTiff;
@end



/// This `R.string.appConst` struct is generated, and contains static references to 6 localization keys.

@interface NSString (AppConst) 

/// Base translation: 刷新
/// 
/// Locales: Base, en, zh-Hans
+ (NSString *)app_Refresh;


/// Base translation: 加载失败，请检查网络链接！
/// 
/// Locales: Base, en, zh-Hans
+ (NSString *)app_NeworkError;


/// Base translation: 升级
/// 
/// Locales: Base, en, zh-Hans
+ (NSString *)app_Update;


/// Base translation: 新增功能:
/// 
/// Locales: Base, en, zh-Hans
+ (NSString *)app_UpdateNewFunction;


/// Base translation: 确定
/// 
/// Locales: Base, en, zh-Hans
+ (NSString *)app_Sure;


/// Base translation: 稍后
/// 
/// Locales: Base, en, zh-Hans
+ (NSString *)app_Latter;
@end



/// UIColor no func and structs

/// UIFont no func and structs

/// UINib no func and structs

/// UINib no func and structs
