//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

#import "R.generated.h"

/// NSObject no func and structs

/// This `R.image` struct is generated, and contains static references to 68 images.
@implementation UIImage (Image) 

/// `[[UIImage imageNamed:@"about_btn_check_nor"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)about_btn_check_nor {
     return [[UIImage imageNamed:@"about_btn_check_nor"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"about_btn_check_nor"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)about_btn_check_norRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"about_btn_check_nor"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"about_btn_check_sel"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)about_btn_check_sel {
     return [[UIImage imageNamed:@"about_btn_check_sel"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"about_btn_check_sel"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)about_btn_check_selRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"about_btn_check_sel"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"account_btn_show_nor"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)account_btn_show_nor {
     return [[UIImage imageNamed:@"account_btn_show_nor"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"account_btn_show_nor"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)account_btn_show_norRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"account_btn_show_nor"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"account_btn_show_sel"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)account_btn_show_sel {
     return [[UIImage imageNamed:@"account_btn_show_sel"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"account_btn_show_sel"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)account_btn_show_selRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"account_btn_show_sel"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"app_icon"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)app_icon {
     return [[UIImage imageNamed:@"app_icon"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"app_icon"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)app_iconRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"app_icon"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"circle_loading"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)circle_loadingRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"circle_loading"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"circle_loading"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)circle_loading {
     return [[UIImage imageNamed:@"circle_loading"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"comment_btn_like_nor"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)comment_btn_like_norRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"comment_btn_like_nor"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"comment_btn_like_nor"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)comment_btn_like_nor {
     return [[UIImage imageNamed:@"comment_btn_like_nor"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"comment_btn_like_sel"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)comment_btn_like_selRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"comment_btn_like_sel"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"comment_btn_like_sel"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)comment_btn_like_sel {
     return [[UIImage imageNamed:@"comment_btn_like_sel"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"comment_shadow"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)comment_shadowRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"comment_shadow"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"comment_shadow"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)comment_shadow {
     return [[UIImage imageNamed:@"comment_shadow"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"launchImage"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)launchImageRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"launchImage"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"launchImage"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)launchImage {
     return [[UIImage imageNamed:@"launchImage"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"list_geng_duo"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)list_geng_duoRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"list_geng_duo"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"list_geng_duo"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)list_geng_duo {
     return [[UIImage imageNamed:@"list_geng_duo"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"list_geng_duo_bai_se"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)list_geng_duo_bai_seRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"list_geng_duo_bai_se"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"list_geng_duo_bai_se"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)list_geng_duo_bai_se {
     return [[UIImage imageNamed:@"list_geng_duo_bai_se"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"loading00000"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00000RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"loading00000"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"loading00000"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00000 {
     return [[UIImage imageNamed:@"loading00000"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"loading00001"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00001 {
     return [[UIImage imageNamed:@"loading00001"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"loading00001"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00001RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"loading00001"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"loading00002"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00002 {
     return [[UIImage imageNamed:@"loading00002"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"loading00002"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00002RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"loading00002"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"loading00003"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00003RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"loading00003"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"loading00003"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00003 {
     return [[UIImage imageNamed:@"loading00003"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"loading00004"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00004 {
     return [[UIImage imageNamed:@"loading00004"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"loading00004"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00004RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"loading00004"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"loading00005"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00005RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"loading00005"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"loading00005"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00005 {
     return [[UIImage imageNamed:@"loading00005"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"loading00006"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00006RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"loading00006"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"loading00006"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00006 {
     return [[UIImage imageNamed:@"loading00006"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"loading00007"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00007RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"loading00007"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"loading00007"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00007 {
     return [[UIImage imageNamed:@"loading00007"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"loading00008"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00008RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"loading00008"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"loading00008"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00008 {
     return [[UIImage imageNamed:@"loading00008"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"loading00009"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00009RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"loading00009"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"loading00009"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00009 {
     return [[UIImage imageNamed:@"loading00009"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"loading00010"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00010RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"loading00010"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"loading00010"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00010 {
     return [[UIImage imageNamed:@"loading00010"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"loading00011"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00011RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"loading00011"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"loading00011"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00011 {
     return [[UIImage imageNamed:@"loading00011"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"loading00012"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00012 {
     return [[UIImage imageNamed:@"loading00012"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"loading00012"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00012RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"loading00012"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"loading00013"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00013RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"loading00013"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"loading00013"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00013 {
     return [[UIImage imageNamed:@"loading00013"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"loading00014"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00014 {
     return [[UIImage imageNamed:@"loading00014"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"loading00014"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00014RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"loading00014"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"loading00015"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00015 {
     return [[UIImage imageNamed:@"loading00015"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"loading00015"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00015RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"loading00015"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"loading00016"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00016 {
     return [[UIImage imageNamed:@"loading00016"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"loading00016"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00016RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"loading00016"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"loading00017"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00017 {
     return [[UIImage imageNamed:@"loading00017"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"loading00017"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00017RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"loading00017"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"loading00018"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00018 {
     return [[UIImage imageNamed:@"loading00018"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"loading00018"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00018RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"loading00018"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"loading00019"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00019 {
     return [[UIImage imageNamed:@"loading00019"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"loading00019"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00019RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"loading00019"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"loading00020"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00020 {
     return [[UIImage imageNamed:@"loading00020"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"loading00020"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00020RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"loading00020"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"loading00021"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00021 {
     return [[UIImage imageNamed:@"loading00021"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"loading00021"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00021RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"loading00021"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"loading00022"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00022 {
     return [[UIImage imageNamed:@"loading00022"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"loading00022"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00022RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"loading00022"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"loading00023"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00023RenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"loading00023"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"loading00023"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00023 {
     return [[UIImage imageNamed:@"loading00023"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"loading_pic"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading_picRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"loading_pic"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"loading_pic"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading_pic {
     return [[UIImage imageNamed:@"loading_pic"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"login_code"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)login_code {
     return [[UIImage imageNamed:@"login_code"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"login_code"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)login_codeRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"login_code"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"login_del"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)login_delRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"login_del"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"login_del"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)login_del {
     return [[UIImage imageNamed:@"login_del"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"login_icon_phone"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)login_icon_phone {
     return [[UIImage imageNamed:@"login_icon_phone"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"login_icon_phone"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)login_icon_phoneRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"login_icon_phone"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"login_icon_qq"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)login_icon_qq {
     return [[UIImage imageNamed:@"login_icon_qq"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"login_icon_qq"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)login_icon_qqRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"login_icon_qq"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"login_icon_wechat"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)login_icon_wechatRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"login_icon_wechat"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"login_icon_wechat"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)login_icon_wechat {
     return [[UIImage imageNamed:@"login_icon_wechat"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"login_icon_weibo"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)login_icon_weiboRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"login_icon_weibo"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"login_icon_weibo"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)login_icon_weibo {
     return [[UIImage imageNamed:@"login_icon_weibo"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"login_phone"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)login_phone {
     return [[UIImage imageNamed:@"login_phone"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"login_phone"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)login_phoneRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"login_phone"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"login_takephoto"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)login_takephotoRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"login_takephoto"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"login_takephoto"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)login_takephoto {
     return [[UIImage imageNamed:@"login_takephoto"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"mine_background"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)mine_backgroundRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"mine_background"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"mine_background"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)mine_background {
     return [[UIImage imageNamed:@"mine_background"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"nav_bar_shadows"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)nav_bar_shadowsRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"nav_bar_shadows"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"nav_bar_shadows"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)nav_bar_shadows {
     return [[UIImage imageNamed:@"nav_bar_shadows"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"nav_ic_back_black"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)nav_ic_back_blackRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"nav_ic_back_black"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"nav_ic_back_black"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)nav_ic_back_black {
     return [[UIImage imageNamed:@"nav_ic_back_black"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"nav_ic_back_white"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)nav_ic_back_whiteRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"nav_ic_back_white"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"nav_ic_back_white"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)nav_ic_back_white {
     return [[UIImage imageNamed:@"nav_ic_back_white"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"none_pic"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)none_pic {
     return [[UIImage imageNamed:@"none_pic"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"none_pic"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)none_picRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"none_pic"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"pic_default_avatar"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)pic_default_avatarRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"pic_default_avatar"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"pic_default_avatar"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)pic_default_avatar {
     return [[UIImage imageNamed:@"pic_default_avatar"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"pic_no_comment"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)pic_no_commentRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"pic_no_comment"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"pic_no_comment"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)pic_no_comment {
     return [[UIImage imageNamed:@"pic_no_comment"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"pic_no_content"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)pic_no_content {
     return [[UIImage imageNamed:@"pic_no_content"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"pic_no_content"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)pic_no_contentRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"pic_no_content"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"project_btn_wechat"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)project_btn_wechat {
     return [[UIImage imageNamed:@"project_btn_wechat"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"project_btn_wechat"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)project_btn_wechatRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"project_btn_wechat"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"selectionHolder"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)selectionHolderRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"selectionHolder"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"selectionHolder"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)selectionHolder {
     return [[UIImage imageNamed:@"selectionHolder"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"sou_suo_zhuang_shi"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)sou_suo_zhuang_shi {
     return [[UIImage imageNamed:@"sou_suo_zhuang_shi"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"sou_suo_zhuang_shi"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)sou_suo_zhuang_shiRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"sou_suo_zhuang_shi"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"tab_bar_fun_nor"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)tab_bar_fun_norRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"tab_bar_fun_nor"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"tab_bar_fun_nor"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)tab_bar_fun_nor {
     return [[UIImage imageNamed:@"tab_bar_fun_nor"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"tab_bar_fun_sel"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)tab_bar_fun_sel {
     return [[UIImage imageNamed:@"tab_bar_fun_sel"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"tab_bar_fun_sel"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)tab_bar_fun_selRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"tab_bar_fun_sel"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"tab_eat_nor"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)tab_eat_nor {
     return [[UIImage imageNamed:@"tab_eat_nor"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"tab_eat_nor"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)tab_eat_norRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"tab_eat_nor"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"tab_eat_sel"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)tab_eat_sel {
     return [[UIImage imageNamed:@"tab_eat_sel"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"tab_eat_sel"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)tab_eat_selRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"tab_eat_sel"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"tab_home_nor"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)tab_home_nor {
     return [[UIImage imageNamed:@"tab_home_nor"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"tab_home_nor"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)tab_home_norRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"tab_home_nor"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"tab_home_sel"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)tab_home_selRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"tab_home_sel"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"tab_home_sel"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)tab_home_sel {
     return [[UIImage imageNamed:@"tab_home_sel"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}


/// `[[UIImage imageNamed:@"tab_mine_nor"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)tab_mine_nor {
     return [[UIImage imageNamed:@"tab_mine_nor"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"tab_mine_nor"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)tab_mine_norRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"tab_mine_nor"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"tab_mine_sel"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)tab_mine_sel {
     return [[UIImage imageNamed:@"tab_mine_sel"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"tab_mine_sel"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)tab_mine_selRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"tab_mine_sel"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"tab_plaint_nor"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)tab_plaint_nor {
     return [[UIImage imageNamed:@"tab_plaint_nor"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"tab_plaint_nor"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)tab_plaint_norRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"tab_plaint_nor"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"tab_plaint_sel"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)tab_plaint_sel {
     return [[UIImage imageNamed:@"tab_plaint_sel"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"tab_plaint_sel"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)tab_plaint_selRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"tab_plaint_sel"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"wo_de_nor"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)wo_de_nor {
     return [[UIImage imageNamed:@"wo_de_nor"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}

/// `[[UIImage imageNamed:@"wo_de_nor"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)wo_de_norRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"wo_de_nor"] imageWithRenderingMode:renderingMode];
}


/// `[[UIImage imageNamed:@"wo_de_sel"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)wo_de_selRenderingMode:(UIImageRenderingMode)renderingMode {
     return [[UIImage imageNamed:@"wo_de_sel"] imageWithRenderingMode:renderingMode];
}

/// `[[UIImage imageNamed:@"wo_de_sel"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)wo_de_sel {
     return [[UIImage imageNamed:@"wo_de_sel"] imageWithRenderingMode:UIImageRenderingModeAutomatic];
}
@end



/// This `R.string.appConst` struct is generated, and contains static references to 62 localization keys.
@implementation NSString (AppConst) 

/// Base translation: MLSProject园
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_HomeTitle {
     return NSLocalizedStringWithDefaultValue(@"App_HomeTitle",@"AppConst",[NSBundle mainBundle],@"MLSProject园",@"");
}


/// Base translation: 上传成功
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_UploadSuccess {
     return NSLocalizedStringWithDefaultValue(@"APP_UploadSuccess",@"AppConst",[NSBundle mainBundle],@"上传成功",@"");
}


/// Base translation: 上拉显示更多...
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_upLoadMore {
     return NSLocalizedStringWithDefaultValue(@"APP_upLoadMore",@"AppConst",[NSBundle mainBundle],@"上拉显示更多...",@"");
}


/// Base translation: 个人中心
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_MineTitle {
     return NSLocalizedStringWithDefaultValue(@"App_MineTitle",@"AppConst",[NSBundle mainBundle],@"个人中心",@"");
}


/// Base translation: 主页
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_Home {
     return NSLocalizedStringWithDefaultValue(@"APP_Home",@"AppConst",[NSBundle mainBundle],@"主页",@"");
}


/// Base translation: 余额：
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_Balance {
     return NSLocalizedStringWithDefaultValue(@"App_Balance",@"AppConst",[NSBundle mainBundle],@"余额：",@"");
}


/// Base translation: 保存
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_Save {
     return NSLocalizedStringWithDefaultValue(@"APP_Save",@"AppConst",[NSBundle mainBundle],@"保存",@"");
}


/// Base translation: 充值
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_Recharge {
     return NSLocalizedStringWithDefaultValue(@"App_Recharge",@"AppConst",[NSBundle mainBundle],@"充值",@"");
}


/// Base translation: 分享失败
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_SharedFailed {
     return NSLocalizedStringWithDefaultValue(@"APP_SharedFailed",@"AppConst",[NSBundle mainBundle],@"分享失败",@"");
}


/// Base translation: 分享成功
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_SharedSuccess {
     return NSLocalizedStringWithDefaultValue(@"APP_SharedSuccess",@"AppConst",[NSBundle mainBundle],@"分享成功",@"");
}


/// Base translation: 刷新
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_Refresh {
     return NSLocalizedStringWithDefaultValue(@"App_Refresh",@"AppConst",[NSBundle mainBundle],@"刷新",@"");
}


/// Base translation: 办卡
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_RegisterNewCard {
     return NSLocalizedStringWithDefaultValue(@"App_RegisterNewCard",@"AppConst",[NSBundle mainBundle],@"办卡",@"");
}


/// Base translation: 办卡充值
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_RegisterAndRecharge {
     return NSLocalizedStringWithDefaultValue(@"App_RegisterAndRecharge",@"AppConst",[NSBundle mainBundle],@"办卡充值",@"");
}


/// Base translation: 加载失败，请检查网络链接！
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_NeworkError {
     return NSLocalizedStringWithDefaultValue(@"App_NeworkError",@"AppConst",[NSBundle mainBundle],@"加载失败，请检查网络链接！",@"");
}


/// Base translation: 努力加载中...
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_refreshIng {
     return NSLocalizedStringWithDefaultValue(@"APP_refreshIng",@"AppConst",[NSBundle mainBundle],@"努力加载中...",@"");
}


/// Base translation: 匿名用户
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_NoNickName {
     return NSLocalizedStringWithDefaultValue(@"App_NoNickName",@"AppConst",[NSBundle mainBundle],@"匿名用户",@"");
}


/// Base translation: 升级
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_Update {
     return NSLocalizedStringWithDefaultValue(@"App_Update",@"AppConst",[NSBundle mainBundle],@"升级",@"");
}


/// Base translation: 卡号：
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_CardNum {
     return NSLocalizedStringWithDefaultValue(@"App_CardNum",@"AppConst",[NSBundle mainBundle],@"卡号：",@"");
}


/// Base translation: 反馈
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_FeedBack {
     return NSLocalizedStringWithDefaultValue(@"App_FeedBack",@"AppConst",[NSBundle mainBundle],@"反馈",@"");
}


/// Base translation: 发送
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_Send {
     return NSLocalizedStringWithDefaultValue(@"App_Send",@"AppConst",[NSBundle mainBundle],@"发送",@"");
}


/// Base translation: 喜欢
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_Like {
     return NSLocalizedStringWithDefaultValue(@"APP_Like",@"AppConst",[NSBundle mainBundle],@"喜欢",@"");
}


/// Base translation: 场地预定
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_Yard {
     return NSLocalizedStringWithDefaultValue(@"APP_Yard",@"AppConst",[NSBundle mainBundle],@"场地预定",@"");
}


/// Base translation: 多赞多精彩
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_MoreSupportAndMoreWonderful {
     return NSLocalizedStringWithDefaultValue(@"APP_MoreSupportAndMoreWonderful",@"AppConst",[NSBundle mainBundle],@"多赞多精彩",@"");
}


/// Base translation: 已经到底啦
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_endRefresh {
     return NSLocalizedStringWithDefaultValue(@"APP_endRefresh",@"AppConst",[NSBundle mainBundle],@"已经到底啦",@"");
}


/// Base translation: 快捷登录
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_ThirdPartyFastLogin {
     return NSLocalizedStringWithDefaultValue(@"APP_ThirdPartyFastLogin",@"AppConst",[NSBundle mainBundle],@"快捷登录",@"");
}


/// Base translation: 意见反馈
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_SuggestionFeedBack {
     return NSLocalizedStringWithDefaultValue(@"App_SuggestionFeedBack",@"AppConst",[NSBundle mainBundle],@"意见反馈",@"");
}


/// Base translation: 我
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_Mine {
     return NSLocalizedStringWithDefaultValue(@"APP_Mine",@"AppConst",[NSBundle mainBundle],@"我",@"");
}


/// Base translation: 我的会员卡
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_MyVipCard {
     return NSLocalizedStringWithDefaultValue(@"App_MyVipCard",@"AppConst",[NSBundle mainBundle],@"我的会员卡",@"");
}


/// Base translation: 我要报名
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_UserSignUp {
     return NSLocalizedStringWithDefaultValue(@"App_UserSignUp",@"AppConst",[NSBundle mainBundle],@"我要报名",@"");
}


/// Base translation: 手机号码
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_PhoneNum {
     return NSLocalizedStringWithDefaultValue(@"APP_PhoneNum",@"AppConst",[NSBundle mainBundle],@"手机号码",@"");
}


/// Base translation: 找回密码
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_FindPwd {
     return NSLocalizedStringWithDefaultValue(@"App_FindPwd",@"AppConst",[NSBundle mainBundle],@"找回密码",@"");
}


/// Base translation: 授权失败
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_AuthorizationFailed {
     return NSLocalizedStringWithDefaultValue(@"App_AuthorizationFailed",@"AppConst",[NSBundle mainBundle],@"授权失败",@"");
}


/// Base translation: 授权成功
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_AuthorizationSuccess {
     return NSLocalizedStringWithDefaultValue(@"App_AuthorizationSuccess",@"AppConst",[NSBundle mainBundle],@"授权成功",@"");
}


/// Base translation: 改密码
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_ChangePwd {
     return NSLocalizedStringWithDefaultValue(@"App_ChangePwd",@"AppConst",[NSBundle mainBundle],@"改密码",@"");
}


/// Base translation: 新办会员卡
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_CreateVipCard {
     return NSLocalizedStringWithDefaultValue(@"App_CreateVipCard",@"AppConst",[NSBundle mainBundle],@"新办会员卡",@"");
}


/// Base translation: 新增功能:
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_UpdateNewFunction {
     return NSLocalizedStringWithDefaultValue(@"App_UpdateNewFunction",@"AppConst",[NSBundle mainBundle],@"新增功能:",@"");
}


/// Base translation: 无内容
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_EmptyContent {
     return NSLocalizedStringWithDefaultValue(@"App_EmptyContent",@"AppConst",[NSBundle mainBundle],@"无内容",@"");
}


/// Base translation: 昵称至少2个字
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_UserNickNameNotValid {
     return NSLocalizedStringWithDefaultValue(@"APP_UserNickNameNotValid",@"AppConst",[NSBundle mainBundle],@"昵称至少2个字",@"");
}


/// Base translation: 更多
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_More {
     return NSLocalizedStringWithDefaultValue(@"App_More",@"AppConst",[NSBundle mainBundle],@"更多",@"");
}


/// Base translation: 最新
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_Newest {
     return NSLocalizedStringWithDefaultValue(@"App_Newest",@"AppConst",[NSBundle mainBundle],@"最新",@"");
}


/// Base translation: 最新评论 (%ld)
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_NewestCommentValue1:(int)value1 {
     return [NSString localizedStringWithFormat:NSLocalizedStringWithDefaultValue(@"APP_NewestComment",@"AppConst",[NSBundle mainBundle],@"最新评论 (%ld)",@""),value1];
}


/// Base translation: 有效期至：
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_RemainTime {
     return NSLocalizedStringWithDefaultValue(@"App_RemainTime",@"AppConst",[NSBundle mainBundle],@"有效期至：",@"");
}


/// Base translation: 未登录
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_NotLogin {
     return NSLocalizedStringWithDefaultValue(@"App_NotLogin",@"AppConst",[NSBundle mainBundle],@"未登录",@"");
}


/// Base translation: 来,做第一个评论的人
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_EmptyComment {
     return NSLocalizedStringWithDefaultValue(@"App_EmptyComment",@"AppConst",[NSBundle mainBundle],@"来,做第一个评论的人",@"");
}


/// Base translation: 松开刷新...
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_stopForRefresh {
     return NSLocalizedStringWithDefaultValue(@"APP_stopForRefresh",@"AppConst",[NSBundle mainBundle],@"松开刷新...",@"");
}


/// Base translation: 注册
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_Register {
     return NSLocalizedStringWithDefaultValue(@"App_Register",@"AppConst",[NSBundle mainBundle],@"注册",@"");
}


/// Base translation: 登录
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_Login {
     return NSLocalizedStringWithDefaultValue(@"App_Login",@"AppConst",[NSBundle mainBundle],@"登录",@"");
}


/// Base translation: 登录成功
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_LoginSuccess {
     return NSLocalizedStringWithDefaultValue(@"APP_LoginSuccess",@"AppConst",[NSBundle mainBundle],@"登录成功",@"");
}


/// Base translation: 短信验证码
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_SMSSecurityCode {
     return NSLocalizedStringWithDefaultValue(@"APP_SMSSecurityCode",@"AppConst",[NSBundle mainBundle],@"短信验证码",@"");
}


/// Base translation: 确定
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_Sure {
     return NSLocalizedStringWithDefaultValue(@"App_Sure",@"AppConst",[NSBundle mainBundle],@"确定",@"");
}


/// Base translation: 稍后
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_Latter {
     return NSLocalizedStringWithDefaultValue(@"App_Latter",@"AppConst",[NSBundle mainBundle],@"稍后",@"");
}


/// Base translation: 立即办理
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_TransactNow {
     return NSLocalizedStringWithDefaultValue(@"App_TransactNow",@"AppConst",[NSBundle mainBundle],@"立即办理",@"");
}


/// Base translation: 精彩评论
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_WonderfulComment {
     return NSLocalizedStringWithDefaultValue(@"APP_WonderfulComment",@"AppConst",[NSBundle mainBundle],@"精彩评论",@"");
}


/// Base translation: 绑定会员卡
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_BindVipCard {
     return NSLocalizedStringWithDefaultValue(@"App_BindVipCard",@"AppConst",[NSBundle mainBundle],@"绑定会员卡",@"");
}


/// Base translation: 绑定手机号
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_WebCatLogin {
     return NSLocalizedStringWithDefaultValue(@"App_WebCatLogin",@"AppConst",[NSBundle mainBundle],@"绑定手机号",@"");
}


/// Base translation: 网络错误，请稍后重试！
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_RequestNormalError {
     return NSLocalizedStringWithDefaultValue(@"App_RequestNormalError",@"AppConst",[NSBundle mainBundle],@"网络错误，请稍后重试！",@"");
}


/// Base translation: 置顶
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_Overhead {
     return NSLocalizedStringWithDefaultValue(@"App_Overhead",@"AppConst",[NSBundle mainBundle],@"置顶",@"");
}


/// Base translation: 获取验证码
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_GetSMSCode {
     return NSLocalizedStringWithDefaultValue(@"APP_GetSMSCode",@"AppConst",[NSBundle mainBundle],@"获取验证码",@"");
}


/// Base translation: 说点儿有趣的...
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_CommentSaySomeThingFuny {
     return NSLocalizedStringWithDefaultValue(@"App_CommentSaySomeThingFuny",@"AppConst",[NSBundle mainBundle],@"说点儿有趣的...",@"");
}


/// Base translation: 请输入正确昵称
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_NickNameError {
     return NSLocalizedStringWithDefaultValue(@"APP_NickNameError",@"AppConst",[NSBundle mainBundle],@"请输入正确昵称",@"");
}


/// Base translation: 赛事活动
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_Event {
     return NSLocalizedStringWithDefaultValue(@"APP_Event",@"AppConst",[NSBundle mainBundle],@"赛事活动",@"");
}


/// Base translation: 退出登录成功
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_LogoutSuccess {
     return NSLocalizedStringWithDefaultValue(@"APP_LogoutSuccess",@"AppConst",[NSBundle mainBundle],@"退出登录成功",@"");
}
@end



/// This `R.string.dZNPhotoPickerController` struct is generated, and contains static references to 15 localization keys.
@implementation NSString (DZNPhotoPickerController) 

/// en translation: 删除
/// 
/// Locales: en, zh-Hans
+ (NSString *)deletePhoto {
     return NSLocalizedStringWithDefaultValue(@"Delete Photo",@"DZNPhotoPickerController",[NSBundle mainBundle],nil,@"");
}


/// en translation: 取消
/// 
/// Locales: en, zh-Hans
+ (NSString *)cancel {
     return NSLocalizedStringWithDefaultValue(@"Cancel",@"DZNPhotoPickerController",[NSBundle mainBundle],nil,@"");
}


/// en translation: 拍照
/// 
/// Locales: en, zh-Hans
+ (NSString *)takePhoto {
     return NSLocalizedStringWithDefaultValue(@"Take Photo",@"DZNPhotoPickerController",[NSBundle mainBundle],nil,@"");
}


/// en translation: 搜索
/// 
/// Locales: en, zh-Hans
+ (NSString *)search {
     return NSLocalizedStringWithDefaultValue(@"Search",@"DZNPhotoPickerController",[NSBundle mainBundle],nil,@"");
}


/// en translation: 搜索 "%@"
/// 
/// Locales: en, zh-Hans
+ (NSString *)searchForValue1:(NSString *)value1 {
     return [NSString localizedStringWithFormat:NSLocalizedStringWithDefaultValue(@"Search for \"%@\"",@"DZNPhotoPickerController",[NSBundle mainBundle],nil,@""),value1];
}


/// en translation: 搜索图片
/// 
/// Locales: en, zh-Hans
+ (NSString *)searchPhoto {
     return NSLocalizedStringWithDefaultValue(@"Search Photo",@"DZNPhotoPickerController",[NSBundle mainBundle],nil,@"");
}


/// en translation: 没有搜索结果
/// 
/// Locales: en, zh-Hans
+ (NSString *)noPhotosFound {
     return NSLocalizedStringWithDefaultValue(@"No Photos Found",@"DZNPhotoPickerController",[NSBundle mainBundle],nil,@"");
}


/// en translation: 确定
/// 
/// Locales: en, zh-Hans
+ (NSString *)oK {
     return NSLocalizedStringWithDefaultValue(@"OK",@"DZNPhotoPickerController",[NSBundle mainBundle],nil,@"");
}


/// en translation: 编辑
/// 
/// Locales: en, zh-Hans
+ (NSString *)editPhoto {
     return NSLocalizedStringWithDefaultValue(@"Edit Photo",@"DZNPhotoPickerController",[NSBundle mainBundle],nil,@"");
}


/// en translation: 缩放
/// 
/// Locales: en, zh-Hans
+ (NSString *)moveAndScale {
     return NSLocalizedStringWithDefaultValue(@"Move and Scale",@"DZNPhotoPickerController",[NSBundle mainBundle],nil,@"");
}


/// en translation: 网络图片
/// 
/// Locales: en, zh-Hans
+ (NSString *)internetPhotos {
     return NSLocalizedStringWithDefaultValue(@"Internet Photos",@"DZNPhotoPickerController",[NSBundle mainBundle],nil,@"");
}


/// en translation: 请输入正确关键词
/// 
/// Locales: en, zh-Hans
+ (NSString *)makeSureThatAllWordsAreSpelledCorrectly {
     return NSLocalizedStringWithDefaultValue(@"Make sure that all words are spelled correctly.",@"DZNPhotoPickerController",[NSBundle mainBundle],nil,@"");
}


/// en translation: 选取
/// 
/// Locales: en, zh-Hans
+ (NSString *)choose {
     return NSLocalizedStringWithDefaultValue(@"Choose",@"DZNPhotoPickerController",[NSBundle mainBundle],nil,@"");
}


/// en translation: 选择图片
/// 
/// Locales: en, zh-Hans
+ (NSString *)choosePhoto {
     return NSLocalizedStringWithDefaultValue(@"Choose Photo",@"DZNPhotoPickerController",[NSBundle mainBundle],nil,@"");
}


/// en translation: 错误
/// 
/// Locales: en, zh-Hans
+ (NSString *)error {
     return NSLocalizedStringWithDefaultValue(@"Error",@"DZNPhotoPickerController",[NSBundle mainBundle],nil,@"");
}
@end



/// This `R.string.localizable` struct is generated, and contains static references to 3 localization keys.
@implementation NSString (Localizable) 

/// zh-Hans translation: 取消
/// 
/// Locales: zh-Hans, en
+ (NSString *)cancel {
     return NSLocalizedStringWithDefaultValue(@"Cancel",nil,[NSBundle mainBundle],nil,@"");
}


/// zh-Hans translation: 拍照
/// 
/// Locales: zh-Hans, en
+ (NSString *)takePhoto {
     return NSLocalizedStringWithDefaultValue(@"Take Photo",nil,[NSBundle mainBundle],nil,@"");
}


/// zh-Hans translation: 相册选择
/// 
/// Locales: zh-Hans, en
+ (NSString *)chooseFromLibrary {
     return NSLocalizedStringWithDefaultValue(@"Choose From Library",nil,[NSBundle mainBundle],nil,@"");
}
@end



/// This `R.string.uS2Localizable` struct is generated, and contains static references to 10 localization keys.
@implementation NSString (US2Localizable) 

/// en translation: Enter a stronger password
/// 
/// Locales: en
+ (NSString *)uS2KeyConditionViolationPasswordStrength {
     return NSLocalizedStringWithDefaultValue(@"US2KeyConditionViolationPasswordStrength",@"US2Localizable",[NSBundle mainBundle],nil,@"");
}


/// en translation: Enter a valid UK post code
/// 
/// Locales: en
+ (NSString *)uS2KeyConditionViolationPostcodeUK {
     return NSLocalizedStringWithDefaultValue(@"US2KeyConditionViolationPostcodeUK",@"US2Localizable",[NSBundle mainBundle],nil,@"");
}


/// en translation: Enter a valid URL in the format http(s)://www.example.com
/// 
/// Locales: en
+ (NSString *)uS2KeyConditionViolationURL {
     return NSLocalizedStringWithDefaultValue(@"US2KeyConditionViolationURL",@"US2Localizable",[NSBundle mainBundle],nil,@"");
}


/// en translation: Enter a valid URL in the format www.example.com
/// 
/// Locales: en
+ (NSString *)uS2KeyConditionViolationShorthandURL {
     return NSLocalizedStringWithDefaultValue(@"US2KeyConditionViolationShorthandURL",@"US2Localizable",[NSBundle mainBundle],nil,@"");
}


/// en translation: Enter letters only
/// 
/// Locales: en
+ (NSString *)uS2KeyConditionViolationAlphabetic {
     return NSLocalizedStringWithDefaultValue(@"US2KeyConditionViolationAlphabetic",@"US2Localizable",[NSBundle mainBundle],nil,@"");
}


/// en translation: Enter minimum %d, maximum %d characters
/// 
/// Locales: en
+ (NSString *)uS2KeyConditionViolationRangeValue1:(int)value1 Value2:(int)value2 {
     return [NSString localizedStringWithFormat:NSLocalizedStringWithDefaultValue(@"US2KeyConditionViolationRange",@"US2Localizable",[NSBundle mainBundle],nil,@""),value1, value2];
}


/// en translation: Enter numbers and letters only
/// 
/// Locales: en
+ (NSString *)uS2KeyConditionViolationAlphanumeric {
     return NSLocalizedStringWithDefaultValue(@"US2KeyConditionViolationAlphanumeric",@"US2Localizable",[NSBundle mainBundle],nil,@"");
}


/// en translation: Enter numbers only
/// 
/// Locales: en
+ (NSString *)uS2KeyConditionViolationNumeric {
     return NSLocalizedStringWithDefaultValue(@"US2KeyConditionViolationNumeric",@"US2Localizable",[NSBundle mainBundle],nil,@"");
}


/// en translation: Enter some text
/// 
/// Locales: en
+ (NSString *)uS2KeyConditionViolationPresent {
     return NSLocalizedStringWithDefaultValue(@"US2KeyConditionViolationPresent",@"US2Localizable",[NSBundle mainBundle],nil,@"");
}


/// en translation: Enter valid email address in the format example@example.com
/// 
/// Locales: en
+ (NSString *)uS2KeyConditionViolationEmail {
     return NSLocalizedStringWithDefaultValue(@"US2KeyConditionViolationEmail",@"US2Localizable",[NSBundle mainBundle],nil,@"");
}
@end



/// UIColor no func and structs

/// UIFont no func and structs

/// UINib no func and structs

/// UINib no func and structs
