//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

/// NSObject no func and structs

/// This `R.image` struct is generated, and contains static references to 68 images.

@interface UIImage (Image) 

/// `[[UIImage imageNamed:@"about_btn_check_nor"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)about_btn_check_nor;

/// `[[UIImage imageNamed:@"about_btn_check_nor"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)about_btn_check_norRenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"about_btn_check_sel"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)about_btn_check_sel;

/// `[[UIImage imageNamed:@"about_btn_check_sel"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)about_btn_check_selRenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"account_btn_show_nor"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)account_btn_show_nor;

/// `[[UIImage imageNamed:@"account_btn_show_nor"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)account_btn_show_norRenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"account_btn_show_sel"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)account_btn_show_sel;

/// `[[UIImage imageNamed:@"account_btn_show_sel"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)account_btn_show_selRenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"app_icon"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)app_icon;

/// `[[UIImage imageNamed:@"app_icon"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)app_iconRenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"circle_loading"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)circle_loadingRenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"circle_loading"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)circle_loading;


/// `[[UIImage imageNamed:@"comment_btn_like_nor"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)comment_btn_like_norRenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"comment_btn_like_nor"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)comment_btn_like_nor;


/// `[[UIImage imageNamed:@"comment_btn_like_sel"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)comment_btn_like_selRenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"comment_btn_like_sel"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)comment_btn_like_sel;


/// `[[UIImage imageNamed:@"comment_shadow"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)comment_shadowRenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"comment_shadow"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)comment_shadow;


/// `[[UIImage imageNamed:@"launchImage"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)launchImageRenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"launchImage"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)launchImage;


/// `[[UIImage imageNamed:@"list_geng_duo"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)list_geng_duoRenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"list_geng_duo"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)list_geng_duo;


/// `[[UIImage imageNamed:@"list_geng_duo_bai_se"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)list_geng_duo_bai_seRenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"list_geng_duo_bai_se"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)list_geng_duo_bai_se;


/// `[[UIImage imageNamed:@"loading00000"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00000RenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"loading00000"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00000;


/// `[[UIImage imageNamed:@"loading00001"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00001;

/// `[[UIImage imageNamed:@"loading00001"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00001RenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"loading00002"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00002;

/// `[[UIImage imageNamed:@"loading00002"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00002RenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"loading00003"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00003RenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"loading00003"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00003;


/// `[[UIImage imageNamed:@"loading00004"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00004;

/// `[[UIImage imageNamed:@"loading00004"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00004RenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"loading00005"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00005RenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"loading00005"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00005;


/// `[[UIImage imageNamed:@"loading00006"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00006RenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"loading00006"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00006;


/// `[[UIImage imageNamed:@"loading00007"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00007RenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"loading00007"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00007;


/// `[[UIImage imageNamed:@"loading00008"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00008RenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"loading00008"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00008;


/// `[[UIImage imageNamed:@"loading00009"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00009RenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"loading00009"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00009;


/// `[[UIImage imageNamed:@"loading00010"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00010RenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"loading00010"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00010;


/// `[[UIImage imageNamed:@"loading00011"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00011RenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"loading00011"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00011;


/// `[[UIImage imageNamed:@"loading00012"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00012;

/// `[[UIImage imageNamed:@"loading00012"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00012RenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"loading00013"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00013RenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"loading00013"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00013;


/// `[[UIImage imageNamed:@"loading00014"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00014;

/// `[[UIImage imageNamed:@"loading00014"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00014RenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"loading00015"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00015;

/// `[[UIImage imageNamed:@"loading00015"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00015RenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"loading00016"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00016;

/// `[[UIImage imageNamed:@"loading00016"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00016RenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"loading00017"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00017;

/// `[[UIImage imageNamed:@"loading00017"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00017RenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"loading00018"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00018;

/// `[[UIImage imageNamed:@"loading00018"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00018RenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"loading00019"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00019;

/// `[[UIImage imageNamed:@"loading00019"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00019RenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"loading00020"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00020;

/// `[[UIImage imageNamed:@"loading00020"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00020RenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"loading00021"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00021;

/// `[[UIImage imageNamed:@"loading00021"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00021RenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"loading00022"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00022;

/// `[[UIImage imageNamed:@"loading00022"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00022RenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"loading00023"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00023RenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"loading00023"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading00023;


/// `[[UIImage imageNamed:@"loading_pic"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading_picRenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"loading_pic"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)loading_pic;


/// `[[UIImage imageNamed:@"login_code"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)login_code;

/// `[[UIImage imageNamed:@"login_code"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)login_codeRenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"login_del"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)login_delRenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"login_del"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)login_del;


/// `[[UIImage imageNamed:@"login_icon_phone"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)login_icon_phone;

/// `[[UIImage imageNamed:@"login_icon_phone"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)login_icon_phoneRenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"login_icon_qq"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)login_icon_qq;

/// `[[UIImage imageNamed:@"login_icon_qq"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)login_icon_qqRenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"login_icon_wechat"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)login_icon_wechatRenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"login_icon_wechat"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)login_icon_wechat;


/// `[[UIImage imageNamed:@"login_icon_weibo"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)login_icon_weiboRenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"login_icon_weibo"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)login_icon_weibo;


/// `[[UIImage imageNamed:@"login_phone"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)login_phone;

/// `[[UIImage imageNamed:@"login_phone"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)login_phoneRenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"login_takephoto"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)login_takephotoRenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"login_takephoto"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)login_takephoto;


/// `[[UIImage imageNamed:@"mine_background"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)mine_backgroundRenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"mine_background"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)mine_background;


/// `[[UIImage imageNamed:@"nav_bar_shadows"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)nav_bar_shadowsRenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"nav_bar_shadows"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)nav_bar_shadows;


/// `[[UIImage imageNamed:@"nav_ic_back_black"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)nav_ic_back_blackRenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"nav_ic_back_black"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)nav_ic_back_black;


/// `[[UIImage imageNamed:@"nav_ic_back_white"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)nav_ic_back_whiteRenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"nav_ic_back_white"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)nav_ic_back_white;


/// `[[UIImage imageNamed:@"none_pic"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)none_pic;

/// `[[UIImage imageNamed:@"none_pic"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)none_picRenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"pic_default_avatar"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)pic_default_avatarRenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"pic_default_avatar"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)pic_default_avatar;


/// `[[UIImage imageNamed:@"pic_no_comment"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)pic_no_commentRenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"pic_no_comment"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)pic_no_comment;


/// `[[UIImage imageNamed:@"pic_no_content"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)pic_no_content;

/// `[[UIImage imageNamed:@"pic_no_content"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)pic_no_contentRenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"project_btn_wechat"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)project_btn_wechat;

/// `[[UIImage imageNamed:@"project_btn_wechat"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)project_btn_wechatRenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"selectionHolder"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)selectionHolderRenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"selectionHolder"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)selectionHolder;


/// `[[UIImage imageNamed:@"sou_suo_zhuang_shi"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)sou_suo_zhuang_shi;

/// `[[UIImage imageNamed:@"sou_suo_zhuang_shi"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)sou_suo_zhuang_shiRenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"tab_bar_fun_nor"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)tab_bar_fun_norRenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"tab_bar_fun_nor"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)tab_bar_fun_nor;


/// `[[UIImage imageNamed:@"tab_bar_fun_sel"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)tab_bar_fun_sel;

/// `[[UIImage imageNamed:@"tab_bar_fun_sel"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)tab_bar_fun_selRenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"tab_eat_nor"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)tab_eat_nor;

/// `[[UIImage imageNamed:@"tab_eat_nor"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)tab_eat_norRenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"tab_eat_sel"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)tab_eat_sel;

/// `[[UIImage imageNamed:@"tab_eat_sel"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)tab_eat_selRenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"tab_home_nor"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)tab_home_nor;

/// `[[UIImage imageNamed:@"tab_home_nor"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)tab_home_norRenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"tab_home_sel"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)tab_home_selRenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"tab_home_sel"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)tab_home_sel;


/// `[[UIImage imageNamed:@"tab_mine_nor"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)tab_mine_nor;

/// `[[UIImage imageNamed:@"tab_mine_nor"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)tab_mine_norRenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"tab_mine_sel"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)tab_mine_sel;

/// `[[UIImage imageNamed:@"tab_mine_sel"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)tab_mine_selRenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"tab_plaint_nor"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)tab_plaint_nor;

/// `[[UIImage imageNamed:@"tab_plaint_nor"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)tab_plaint_norRenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"tab_plaint_sel"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)tab_plaint_sel;

/// `[[UIImage imageNamed:@"tab_plaint_sel"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)tab_plaint_selRenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"wo_de_nor"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)wo_de_nor;

/// `[[UIImage imageNamed:@"wo_de_nor"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)wo_de_norRenderingMode:(UIImageRenderingMode)renderingMode;


/// `[[UIImage imageNamed:@"wo_de_sel"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)wo_de_selRenderingMode:(UIImageRenderingMode)renderingMode;

/// `[[UIImage imageNamed:@"wo_de_sel"] imageWithRenderingMode:renderingMode]`
+ (UIImage *)wo_de_sel;
@end



/// This `R.string.appConst` struct is generated, and contains static references to 62 localization keys.

@interface NSString (AppConst) 

/// Base translation: 上传成功
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_UploadSuccess;


/// Base translation: 上拉显示更多...
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_upLoadMore;


/// Base translation: 个人中心
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_MineTitle;


/// Base translation: 主页
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_Home;


/// Base translation: 余额：
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_Balance;


/// Base translation: 保存
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_Save;


/// Base translation: 充值
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_Recharge;


/// Base translation: 分享失败
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_SharedFailed;


/// Base translation: 分享成功
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_SharedSuccess;


/// Base translation: 刷新
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_Refresh;


/// Base translation: 办卡
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_RegisterNewCard;


/// Base translation: 办卡充值
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_RegisterAndRecharge;


/// Base translation: 加载失败，请检查网络链接！
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_NeworkError;


/// Base translation: 努力加载中...
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_refreshIng;


/// Base translation: 匿名用户
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_NoNickName;


/// Base translation: 升级
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_Update;


/// Base translation: 卡号：
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_CardNum;


/// Base translation: 反馈
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_FeedBack;


/// Base translation: 发送
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_Send;


/// Base translation: 喜欢
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_Like;


/// Base translation: 场地预定
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_Yard;


/// Base translation: 多赞多精彩
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_MoreSupportAndMoreWonderful;


/// Base translation: 已经到底啦
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_endRefresh;


/// Base translation: 快捷登录
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_ThirdPartyFastLogin;


/// Base translation: 意见反馈
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_SuggestionFeedBack;


/// Base translation: 我
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_Mine;


/// Base translation: 我的会员卡
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_MyVipCard;


/// Base translation: 我要报名
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_UserSignUp;


/// Base translation: 手机号码
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_PhoneNum;


/// Base translation: 找回密码
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_FindPwd;


/// Base translation: 授权失败
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_AuthorizationFailed;


/// Base translation: 授权成功
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_AuthorizationSuccess;


/// Base translation: 改密码
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_ChangePwd;


/// Base translation: 新办会员卡
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_CreateVipCard;


/// Base translation: 新增功能:
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_UpdateNewFunction;


/// Base translation: 无内容
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_EmptyContent;


/// Base translation: 昵称至少2个字
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_UserNickNameNotValid;


/// Base translation: 更多
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_More;


/// Base translation: 最新
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_Newest;


/// Base translation: 最新评论 (%ld)
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_NewestCommentValue1:(int)value1;


/// Base translation: 有效期至：
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_RemainTime;


/// Base translation: 未登录
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_NotLogin;


/// Base translation: 李宁体育园
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_HomeTitle;


/// Base translation: 来,做第一个评论的人
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_EmptyComment;


/// Base translation: 松开刷新...
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_stopForRefresh;


/// Base translation: 注册
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_Register;


/// Base translation: 登录
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_Login;


/// Base translation: 登录成功
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_LoginSuccess;


/// Base translation: 短信验证码
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_SMSSecurityCode;


/// Base translation: 确定
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_Sure;


/// Base translation: 稍后
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_Latter;


/// Base translation: 立即办理
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_TransactNow;


/// Base translation: 精彩评论
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_WonderfulComment;


/// Base translation: 绑定会员卡
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_BindVipCard;


/// Base translation: 绑定手机号
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_WebCatLogin;


/// Base translation: 网络错误，请稍后重试！
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_RequestNormalError;


/// Base translation: 置顶
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_Overhead;


/// Base translation: 获取验证码
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_GetSMSCode;


/// Base translation: 说点儿有趣的...
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)app_CommentSaySomeThingFuny;


/// Base translation: 请输入正确昵称
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_NickNameError;


/// Base translation: 赛事活动
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_Event;


/// Base translation: 退出登录成功
/// 
/// Locales: zh-Hans, en, Base
+ (NSString *)aPP_LogoutSuccess;
@end



/// This `R.string.dZNPhotoPickerController` struct is generated, and contains static references to 15 localization keys.

@interface NSString (DZNPhotoPickerController) 

/// en translation: 删除
/// 
/// Locales: en, zh-Hans
+ (NSString *)deletePhoto;


/// en translation: 取消
/// 
/// Locales: en, zh-Hans
+ (NSString *)cancel;


/// en translation: 拍照
/// 
/// Locales: en, zh-Hans
+ (NSString *)takePhoto;


/// en translation: 搜索
/// 
/// Locales: en, zh-Hans
+ (NSString *)search;


/// en translation: 搜索 "%@"
/// 
/// Locales: en, zh-Hans
+ (NSString *)searchForValue1:(NSString *)value1;


/// en translation: 搜索图片
/// 
/// Locales: en, zh-Hans
+ (NSString *)searchPhoto;


/// en translation: 没有搜索结果
/// 
/// Locales: en, zh-Hans
+ (NSString *)noPhotosFound;


/// en translation: 确定
/// 
/// Locales: en, zh-Hans
+ (NSString *)oK;


/// en translation: 编辑
/// 
/// Locales: en, zh-Hans
+ (NSString *)editPhoto;


/// en translation: 缩放
/// 
/// Locales: en, zh-Hans
+ (NSString *)moveAndScale;


/// en translation: 网络图片
/// 
/// Locales: en, zh-Hans
+ (NSString *)internetPhotos;


/// en translation: 请输入正确关键词
/// 
/// Locales: en, zh-Hans
+ (NSString *)makeSureThatAllWordsAreSpelledCorrectly;


/// en translation: 选取
/// 
/// Locales: en, zh-Hans
+ (NSString *)choose;


/// en translation: 选择图片
/// 
/// Locales: en, zh-Hans
+ (NSString *)choosePhoto;


/// en translation: 错误
/// 
/// Locales: en, zh-Hans
+ (NSString *)error;
@end



/// This `R.string.localizable` struct is generated, and contains static references to 3 localization keys.

@interface NSString (Localizable) 

/// zh-Hans translation: 取消
/// 
/// Locales: zh-Hans, en
+ (NSString *)cancel;


/// zh-Hans translation: 拍照
/// 
/// Locales: zh-Hans, en
+ (NSString *)takePhoto;


/// zh-Hans translation: 相册选择
/// 
/// Locales: zh-Hans, en
+ (NSString *)chooseFromLibrary;
@end



/// This `R.string.uS2Localizable` struct is generated, and contains static references to 10 localization keys.

@interface NSString (US2Localizable) 

/// en translation: Enter a stronger password
/// 
/// Locales: en
+ (NSString *)uS2KeyConditionViolationPasswordStrength;


/// en translation: Enter a valid UK post code
/// 
/// Locales: en
+ (NSString *)uS2KeyConditionViolationPostcodeUK;


/// en translation: Enter a valid URL in the format http(s)://www.example.com
/// 
/// Locales: en
+ (NSString *)uS2KeyConditionViolationURL;


/// en translation: Enter a valid URL in the format www.example.com
/// 
/// Locales: en
+ (NSString *)uS2KeyConditionViolationShorthandURL;


/// en translation: Enter letters only
/// 
/// Locales: en
+ (NSString *)uS2KeyConditionViolationAlphabetic;


/// en translation: Enter minimum %d, maximum %d characters
/// 
/// Locales: en
+ (NSString *)uS2KeyConditionViolationRangeValue1:(int)value1 Value2:(int)value2;


/// en translation: Enter numbers and letters only
/// 
/// Locales: en
+ (NSString *)uS2KeyConditionViolationAlphanumeric;


/// en translation: Enter numbers only
/// 
/// Locales: en
+ (NSString *)uS2KeyConditionViolationNumeric;


/// en translation: Enter some text
/// 
/// Locales: en
+ (NSString *)uS2KeyConditionViolationPresent;


/// en translation: Enter valid email address in the format example@example.com
/// 
/// Locales: en
+ (NSString *)uS2KeyConditionViolationEmail;
@end



/// UIColor no func and structs

/// UIFont no func and structs

/// UINib no func and structs

/// UINib no func and structs
